<?php

declare(strict_types=1);
namespace Bambamboole\FilamentPages\Renderer;

use Bambamboole\FilamentPages\Facades\FilamentPages;
use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\Attributes\AttributesExtension;
use League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension;
use League\CommonMark\Extension\ExternalLink\ExternalLinkExtension;
use League\CommonMark\Extension\FrontMatter\FrontMatterExtension;
use League\CommonMark\Extension\FrontMatter\Output\RenderedContentWithFrontMatter;
use League\CommonMark\Extension\GithubFlavoredMarkdownExtension;
use League\CommonMark\Extension\HeadingPermalink\HeadingPermalinkExtension;
use League\CommonMark\Extension\TableOfContents\TableOfContentsExtension;
use League\CommonMark\MarkdownConverter;
use RyanChandler\CommonmarkBladeBlock\BladeExtension;
use Torchlight\Commonmark\V2\TorchlightExtension;

class MarkdownRenderer
{
    public function convert(
        string $markdown,
        bool $withToc = false,
        bool $withHeadingPermalinks = false,
        bool $withExternalLinks = true,
    ): MarkdownResult {
        // ToC depends on heading IDs generated by the permalink extension
        if ($withToc) {
            $withHeadingPermalinks = true;
        }

        $markdownConfig = FilamentPages::markdownConfig();
        $config = $this->buildConfig($markdownConfig, $withToc, $withHeadingPermalinks, $withExternalLinks);

        $environment = new Environment($config);
        $environment->addExtension(new CommonMarkCoreExtension);
        $environment->addExtension(new GithubFlavoredMarkdownExtension);

        if ($withHeadingPermalinks) {
            $environment->addExtension(new HeadingPermalinkExtension);
        }

        if ($withExternalLinks) {
            $environment->addExtension(new ExternalLinkExtension);
        }

        $environment->addExtension(new FrontMatterExtension);
        $environment->addExtension(new AttributesExtension);

        if ($withToc) {
            $environment->addExtension(new TableOfContentsExtension);
        }

        if (($markdownConfig['blade_blocks'] ?? true) && class_exists(BladeExtension::class)) {
            $environment->addExtension(new BladeExtension);
        }

        if (($markdownConfig['torchlight'] ?? false) && class_exists(TorchlightExtension::class)) {
            $environment->addExtension(new TorchlightExtension);
        }

        $converter = new MarkdownConverter($environment);
        $result = $converter->convert($markdown);

        $frontMatter = $result instanceof RenderedContentWithFrontMatter
            ? ($result->getFrontMatter() ?? [])
            : [];

        $html = $result->getContent();
        $tocHtml = '';

        if ($withToc) {
            $tocClass = $markdownConfig['table_of_contents']['html_class'] ?? 'table-of-contents';
            $tocHtml = $this->extractToc($html, $tocClass);
        }

        return new MarkdownResult(
            html: $html,
            tocHtml: $tocHtml,
            frontMatter: $frontMatter,
        );
    }

    /**
     * @param  array<string, mixed>  $markdownConfig
     * @return array<string, mixed>
     */
    private function buildConfig(array $markdownConfig, bool $withToc, bool $withHeadingPermalinks, bool $withExternalLinks): array
    {
        $config = [];

        if ($withHeadingPermalinks) {
            $permalinkConfig = $markdownConfig['heading_permalink'] ?? [];

            $config['heading_permalink'] = [
                'html_class' => $permalinkConfig['html_class'] ?? 'heading-permalink',
                'symbol' => $permalinkConfig['symbol'] ?? '#',
                'insert' => $permalinkConfig['insert'] ?? 'after',
                'id_prefix' => $permalinkConfig['id_prefix'] ?? 'content',
                'fragment_prefix' => $permalinkConfig['fragment_prefix'] ?? 'content',
                'apply_id_to_heading' => $permalinkConfig['apply_id_to_heading'] ?? false,
                'heading_class' => $permalinkConfig['heading_class'] ?? '',
                'title' => $permalinkConfig['title'] ?? 'Permalink',
                'aria_hidden' => $permalinkConfig['aria_hidden'] ?? true,
                'min_heading_level' => $permalinkConfig['min_heading_level'] ?? 1,
                'max_heading_level' => $permalinkConfig['max_heading_level'] ?? 6,
            ];
        }

        if ($withExternalLinks) {
            $externalLinkConfig = $markdownConfig['external_link'] ?? [];

            $appHost = parse_url((string) config('app.url', ''), PHP_URL_HOST);
            $internalHosts = array_values(array_filter(array_merge(
                (array) ($externalLinkConfig['internal_hosts'] ?? []),
                [$appHost],
            )));

            $config['external_link'] = [
                'internal_hosts' => $internalHosts,
                'open_in_new_window' => $externalLinkConfig['open_in_new_window'] ?? true,
                'html_class' => $externalLinkConfig['html_class'] ?? 'external-link',
                'nofollow' => $externalLinkConfig['nofollow'] ?? 'external',
                'noopener' => $externalLinkConfig['noopener'] ?? 'external',
                'noreferrer' => $externalLinkConfig['noreferrer'] ?? 'external',
            ];
        }

        if ($withToc) {
            $tocConfig = $markdownConfig['table_of_contents'] ?? [];

            $config['table_of_contents'] = [
                'html_class' => $tocConfig['html_class'] ?? 'table-of-contents',
                'position' => 'top',
                'style' => $tocConfig['style'] ?? 'bullet',
                'normalize' => $tocConfig['normalize'] ?? 'relative',
                'min_heading_level' => $tocConfig['min_heading_level'] ?? 2,
                'max_heading_level' => $tocConfig['max_heading_level'] ?? 6,
            ];
        }

        if (isset($markdownConfig['renderer'])) {
            $config['renderer'] = $markdownConfig['renderer'];
        }

        return $config;
    }

    private function extractToc(string &$html, string $tocClass): string
    {
        $openTag = '<ul class="'.$tocClass.'">';
        $startPos = strpos($html, $openTag);

        if ($startPos === false) {
            return '';
        }

        // Walk through the HTML tracking nested <ul> depth to find the matching </ul>
        $depth = 0;
        $pos = $startPos;
        $len = strlen($html);

        while ($pos < $len) {
            $nextOpen = strpos($html, '<ul', $pos + 1);
            $nextClose = strpos($html, '</ul>', $pos + 1);

            if ($nextClose === false) {
                break;
            }

            if ($nextOpen !== false && $nextOpen < $nextClose) {
                $depth++;
                $pos = $nextOpen;
            } else {
                if ($depth === 0) {
                    $endPos = $nextClose + strlen('</ul>');
                    $tocHtml = substr($html, $startPos, $endPos - $startPos);
                    $html = substr($html, 0, $startPos).substr($html, $endPos);

                    return $tocHtml;
                }
                $depth--;
                $pos = $nextClose;
            }
        }

        return '';
    }
}
